### ISSUE TITLE
Add more tests to increase code coveage

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/clang-tools-pip#1]

**Comment by 2bndy5** [comment]
I just want to mention that we don't need to calculate coverage for the test modules because some of that code should only be conditionally triggered (eg in case of a unexpected failure).

**Comment by 2bndy5** [comment]
Just wanted to mention that I have coverage up to >90% on my pro-revision branch: https://app.codecov.io/gh/cpp-linter/clang-tools-pip/commits?branch=pro-revision

**Comment by shenxianpeng** [comment]
Resolved in https://github.com/cpp-linter/clang-tools-pip/pull/16
