### ISSUE TITLE
Better path defaults

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/clang-tools-pip#15]
This thread is for exploring less intrusive paths default values (paths that don't require admin privileges.

On Linux, the default is `~/.local/bin`, but this path doesn't seem to be part of the PATH env var by default. On a fresh Ubuntu install, this path doesn't exist.

Currently, for macosx and windows, the default path is the same as the python executable. This isn't bad if the user is working in a venv, but it requires admin privileges otherwise.

I think we should do a check to see if the selected install path (either default or user-selected) is in the OS env var `PATH`. If it isn't, then we can warn the user that the install path is not in the `PATH` env var (similar to what pip does).

If the install path is not in the env var `PATH`, we might also want to skip the check to see if the tool is already installed.

**Comment by shenxianpeng** [comment]
Couldn't agree more. Thanks for bringing it up.

**Comment by 2bndy5** [comment]
I've already added a warning to notify the user if the install path is not in the env var `PATH` (on my pro-revision branch).

**Comment by 2bndy5** [comment]
I found this python module called [appdirs](https://pypi.org/project/appdirs/) which seems close to what we want, but it is oriented on user data caches in a platform-agnostic way. The description has a good [references about Linux standards](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) though.
