### ISSUE TITLE
The targer link is incorrect when clang-tools was not installed to the default path

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/clang-tools-pip#23]
For example, when the clang-tools were installed with `apt-get install` command (on Ubuntu)
Actual target path is: `/usr/bin/clang-format-10`

```bash
(myenv) ubuntu@CN-L:~/clang-tools-pip$ which clang-format-10
/usr/bin/clang-format-10
(myenv) ubuntu@CN-L:~/clang-tools-pip$ clang-tools -i 10
clang-format-10 already installed
clang-tidy-10 already installed
```

But expect target link is: `/home/ubuntu/.local/bin/clang-format-10`, see the code snippet

https://github.com/cpp-linter/clang-tools-pip/blob/a4f8c90f8abdab261bb58451e0200bfb1bcba06d/clang_tools/install.py#L127

So program will not find a exist link under `/home/ubuntu/.local/bin/`, so it will create a link `/home/ubuntu/.local/bin/clang-format` to `/home/ubuntu/.local/bin/clang-format-10` (it's a link not a executble), and it dons't work when run `clang-format --version`

**Comment by 2bndy5** [comment]
Sorry, I didn't see this issue.

**Comment by 2bndy5** [comment]
Re-posting the proposed solution from #20

> To find the binary installed via `apt`, we could use `which clang-*-<version>`, but this is Linux/OSX specific. In Windows, this is equivalent to `where` in DOS prompt or `Get-Command` in PowerShell.
> 
> However, I think you're only concerned with the binaries that we're installing with this pkg. In that case I think the real solution to this issue is:
> 
> ```diff
> --- a/clang_tools/install.py
> +++ b/clang_tools/install.py
> @@ -59,8 +59,7 @@ def clang_tools_binary_url(
> 
>  def install_tool(tool_name: str, version: str, directory: str) -> bool:
>      """An abstract function that can install either clang-tidy or clang-format."""
> -    if is_installed(tool_name, version):
> -        # TODO should probably skip this if `directory` is not in the PATH env var.
> +    if Path(directory, f"{tool_name}-{version}{suffix}").exists():
>          print(f"{tool_name}-{version}", "already installed")
>          return False
>      bin_url = clang_tools_binary_url(tool_name, version)
> @@ -162,5 +161,6 @@ def install_clang_tools(version: str, directory: str, overwrite: bool) -> None:
>              f"directory is not in your environment variable PATH.{RESET_COLOR}",
>          )
>      for tool_name in ("clang-format", "clang-tidy"):
> -        if install_tool(tool_name, version, install_dir):
> +        target_downloaded = install_tool(tool_name, version, install_dir)
> +        if target_downloaded or (not target_downloaded and overwrite):
>              create_sym_link(tool_name, version, install_dir, overwrite)
> ```
> 
> But this will ignore anything that's already in the PATH env var. So, again, I think this issue is leading to "How to manage the installed binaries?"
