### ISSUE TITLE
Switch to cpp-linter/clang-tools-static-binaries to download clang-tools

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/clang-tools-pip#56]
I think it's time to switch from [muttleyxd/clang-tools-static-binaries](https://github.com/muttleyxd/clang-tools-static-binaries) to [cpp-linter/clang-tools-static-binaries](https://github.com/cpp-linter/clang-tools-static-binaries) @2bndy5 

We have known issues about clang-tidy-14, clang-tidy-15, and clang-tidy-16 having Segmentation faults on Ubuntu 22.02, but after we forked clang-tools-static-binaries repo, made some changes (dropped old version and upgrade build system version)rebuilt by ourselves, the Segmentation faults not existing anymore. 

Here is my manual test on AlmaLinux release 8.9, our build clang-tidy-14 works.

```bash
# download from https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-8f72ab3c/clang-tidy-14_linux-amd64 
bash-4.4$ ./clang-tidy-14_linux-amd64 --version
Segmentation fault (core dumped)

# download from https://github.com/cpp-linter/clang-tools-static-binaries/releases/download/master-be694ee7/clang-query-14_linux-amd64
bash-4.4$ ./clang-tidy-14_linux-amd64 --version
LLVM (http://llvm.org/):
  LLVM version 14.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake-avx512
bash-4.4$
```

[Please see more installation test on Linux, Windows, and MacOS from clang version 7 to 17]( https://github.com/cpp-linter/clang-tools-static-binaries/actions/runs/7442373808)

I don't exactly know the resean why this issue https://github.com/muttleyxd/clang-tools-static-binaries/issues/18 was gone, the most likely reason is that we upgraded the Linux runner from the original `ubuntu-20.04` to `ubuntu-22.04`.

**Comment by 2bndy5** [comment]
> the Segmentation faults not existing anymore

Awesome! I'm all in.

> [Please see more installation test on Linux, Windows, and MacOS from clang version 7 to 17](https://github.com/cpp-linter/clang-tools-static-binaries/actions/runs/7442373808)

I see you tested all on x86_64 architectures. I'm curious if we should warn in the README about architectures that are not supported (like arm64 aka aarch64 and x86). 
> ![](https://img.shields.io/badge/platform-linux--64%20%7C%20win--64%20%7C%20osx--64%20-blue)

Maybe the badge is enough?

> I don't exactly resean why this issue https://github.com/muttleyxd/clang-tools-static-binaries/issues/18 was fixed, the most likely reason is that we upgraded our Linux build system from the original ubuntu-20.04 to ubuntu-22.04.

The error would still surface on Linux runners that use older versions of libc. At least that was my understanding.

---
Lastly, all clang-tidy v14+ builds for MacOS are still ~1.8 GB in size.

**Comment by 2bndy5** [comment]
I'm in bed now, but the keyboard tends to follow me around... 🤣
