### ISSUE TITLE
Find clang tools binaries on macOS instead of installing faulty binaries

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/clang-tools-pip#97]
Apparently LLVM 15 is already installed on macos-latest runners. However, clang-tools-pip pkg fails to find the clang tools' binaries and installs the faulty static binary instead.

_Originally posted by @2bndy5 in https://github.com/cpp-linter/cpp-linter-action/issues/237#issuecomment-2143420115_

**Comment by 2bndy5** [comment]
It turns out that the problem is more complex. See [this comment](https://github.com/cpp-linter/clang-tools-pip/pull/98#issuecomment-2146535374).
